# Generated by Django 5.2.7 on 2026-06-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False)),
                ('frecuencia', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual')], default='semanal', max_length=20)),
            ],
            options={
                'verbose_name': 'Configuración de Notificación',
                'verbose_name_plural': 'Configuraciones de Notificación',
            },
        ),
    ]
