# Generated by Django 5.2.7 on 2025-11-08 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0002_alter_cliente_nombre_alter_proveedor_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='archivado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='archivado',
            field=models.BooleanField(default=False),
        ),
    ]
