# Generated by Django 5.2.7 on 2025-11-13 21:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartado_credito', '0001_initial'),
        ('dominios_comunes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartado',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartado',
            name='monto_pendiente',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='apartado',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='credito',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='credito',
            name='monto_pendiente',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='credito',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddConstraint(
            model_name='apartado',
            constraint=models.CheckConstraint(condition=models.Q(('monto_pendiente__lte', models.F('monto_total'))), name='apartado_monto_pendiente_valid'),
        ),
        migrations.AddConstraint(
            model_name='credito',
            constraint=models.CheckConstraint(condition=models.Q(('monto_pendiente__lte', models.F('monto_total'))), name='credito_monto_pendiente_valid'),
        ),
    ]
