# Generated by Django 5.2.7 on 2025-11-03 21:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra_venta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='precio_por_gramo',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='gramo_ganancia',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='precio_por_gramo',
        ),
        migrations.AddField(
            model_name='compraprenda',
            name='precio_por_gramo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='compraprenda',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='ventaprenda',
            name='gramo_ganancia',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.1'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='ventaprenda',
            name='precio_por_gramo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='ventaprenda',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='compra',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
