# Generated by Django 5.2.7 on 2025-11-24 00:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartado_credito', '0002_apartado_descripcion_apartado_monto_pendiente_and_more'),
        ('compra_venta', '0002_remove_compra_precio_por_gramo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cierre', models.CharField(choices=[('D', 'Diario'), ('M', 'Mensual')], max_length=1)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('fecha_cierre', models.DateTimeField(auto_now_add=True)),
                ('total_entradas', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_salidas', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('saldo_final', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cerrado_por', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Cierre de Caja',
                'verbose_name_plural': 'Cierres de Caja',
                'db_table': 'caja_cierre',
                'ordering': ['-fecha_cierre'],
            },
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria',
                'verbose_name_plural': 'Cuentas Bancarias',
                'db_table': 'caja_cuenta_bancaria',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('E', 'Entrada'), ('S', 'Salida')], max_length=1)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Movimiento',
                'verbose_name_plural': 'Tipos de Movimientos',
                'db_table': 'caja_tipo_movimiento',
            },
        ),
        migrations.CreateModel(
            name='SaldoCuentaPorCierre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cierre_caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos_cuentas', to='caja.cierrecaja')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saldos_historicos', to='caja.cuentabancaria')),
            ],
            options={
                'verbose_name': 'Saldo de Cuenta por Cierre',
                'verbose_name_plural': 'Saldos de Cuentas por Cierre',
                'db_table': 'caja_saldo_cuenta_cierre',
                'unique_together': {('cierre_caja', 'cuenta')},
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cierre_caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='caja.cierrecaja')),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='compra_venta.compra')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='caja.cuentabancaria')),
                ('cuota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='apartado_credito.cuota')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='compra_venta.venta')),
                ('tipo_movimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='caja.tipomovimiento')),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
                'db_table': 'caja_movimiento',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['-fecha'], name='caja_movimi_fecha_c9c59e_idx'), models.Index(fields=['cuenta', '-fecha'], name='caja_movimi_cuenta__1bcebc_idx')],
            },
        ),
    ]
