# Generated by Django 5.2.7 on 2025-11-25 01:12

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientocaja',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
