# Generated by Django 5.2.7 on 2025-11-27 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_alter_movimientocaja_monto'),
        ('egreso_ingreso', '0002_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='egreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='egreso_ingreso.egreso'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='ingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='egreso_ingreso.ingreso'),
        ),
    ]
